version: '3.8'

services:
  api:
    build: .
    container_name: jobtrack
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/jobtrack
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start

  db:
    image: postgres:15
    container_name: jobtrack_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jobtrack
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: